### ISSUE TITLE
DP implementation

### ISSUE THREAD

**Issue by qualmluc** [Luc4sQ/JML-SAT#4]

**Comment by JWittkat** [comment]
I have pushed the code for the dp algorithm. I tried to implement it the way described in the book.
It's working for small test data but when I try to run it with a cnf with 20 variables it takes too long to return something. I don't know if it just really takes this long or if I have a bug in my code I can't find.

**Comment by qualmluc** [comment]
I've watched further into your code and tested more widely examples.

I've found out, that it's closely related to order. I've implemented in your "orderOfVariables" method
```
def orderOfVariables(properties):
    order = []
    for var in range(1,properties[2]+1):
        order.append(var)
    #return order
    orderrenewed = list(np.random.permutation(order))
    print(orderrenewed)
    return orderrenewed
```
a way for me to randomize the order (random permutation of standard order). i used this a few times and it got sometimes significantly faster. But got a weird error, where a cnf is evaluated as false, where it should be true. further i got as an output:
```
PS C:\Users\lucas\Desktop\logik\JML-SAT> python main.py -dp ../../uf20-056.cnf
[12, 9, 18, 6, 4, 7, 2, 1, 19, 20, 17, 10, 5, 11, 13, 8, 14, 3, 15, 16] (print of permuation)
False in 0.62852 Sekunden!

PS C:\Users\lucas\Desktop\logik\JML-SAT> python main.py -udpll ../../uf20-056.cnf
True in 0.01087 Sekunden!
The following variable assignment satisfies input cnf: {1: True, 4: True, 5: True, 7: True, 8: True, 10: True, 13: True, 14: True, 16: True, 17: True, 19: True, -20: False, -18: False, -15: False, -12: False, -9: False, -6: False, -3: False, -2: False}
```

**Comment by qualmluc** [comment]
(die cnf die ich benutzt habe)
[testfile.txt](https://github.com/Luc4sQ/JML-SAT/files/11646682/testfile.txt)

**Comment by JWittkat** [comment]
I had the problem with other data too, when I changed the order. And I think I have found the problem for the wrong decision. I was not checking, if a clause contains a tautology and therefore the resolution was not always right.
